User dashboard #52
amarbajric/EBUSA-AIM17 pull request #107
Opened 2018-06-25 19:07 UTC by dietrich14

first PR
resolves #52 

Notes: 
- temporary endpoints for all tabs (myProcesses = all processes in the store - should be only the ones from the organization; processes in approval = all processes which are not yet approved - should be only the ones from the current user; approved processes = all processes which are already approved - should be only the ones from the current user)
- temporary processes in the news section as well

2018-06-25 19:56 UTC, amarbajric commented
**Review**
- Mixing german and english is not very intuitive and could lead to confusion.
  - Please change the language of the UI for your component to english
- Should there be an `Create Organization` button somewhere or will this not be part of the dashboard component?

Other than that, it looks promising to me and can be approved as soon as the points mentioned above are implemented/discussed.

2018-06-25 19:57 UTC, amarbajric requested changes
See comment above

2018-06-25 20:02 UTC, tortmann commented
I definitely agree with the @amarbajric point to not mix DE and EN i forgot to mention that during our call today when we discussed the wording of the tabs to need changing

2018-06-26 23:24 UTC, amarbajric approved these changes

2018-06-26 23:24 UTC, merged