Approval view #87
amarbajric/EBUSA-AIM17 pull request #90
Opened 2018-06-03 16:23 UTC by Graf-Carello

resolves #87
This is the initial implementation of the approval page. Further To-Do is to implement the actual API calls to the specific endpoints to use real data instead of test data.

2018-06-04 13:37 UTC, amarbajric commented
At first glance the idea is kinda acceptable. 
Nevertheless, there are some aspects which need refactoring and adaptations.

**1.**
This section should be the parent component (i.e. this is what an approver should see if he visits the tab `Approval Page`.)
![screen shot 2018-06-04 at 15 26 16](https://user-images.githubusercontent.com/15001225/40920213-2a3f531c-680c-11e8-9736-bf49cd45a08c.png)

This section should be something like the approval-details page (i.e. when the approver selects one process from the list illustrated in the picture above)
![screen shot 2018-06-04 at 15 26 56](https://user-images.githubusercontent.com/15001225/40920312-6afd92c4-680c-11e8-814d-4d79ef7e7cbd.png)

**ToDo:**
- Split the list of processes which need approval and the process-details section into parent and child component
  - parent component => list of processes which need approval (with a simple list which shows user who uploaded it, name of process, description)
  - child component => if you click on one of the processes (that need approval) in the list of the parent component, another view should load where the information of the process and the user is shown, and where all comments are shown and the commenting, approve and rejection section should be at the bottom

**NOTE:**
As the process store is not yet implemented, it is only required to do the tasks mentioned above. Logic and final implementation hast to wait until the backend is ready. Best case scenario would be however, if you just take some mockup data and test it with them (just look up some tuts. on how to create mockup data in Angular)

2018-06-04 13:39 UTC, amarbajric requested changes
Please fix and/or implement the requested changes which can be found in the comment above.
If done, push your changes to this branch and notify me.

2018-06-04 13:39 UTC, amarbajric commented on GUI-dev/src/app/pages/approval/approval.component.html
> +    -----------------------------------------
What should this do or be?

2018-06-05 16:56 UTC, Graf-Carello commented
I implemented your requested changes now and pushed them to my feature branch.

2018-06-21 12:57 UTC, amarbajric commented
For me it is still incomplete.
To avoid redundancy in the comments, please check my previous request (comment) on how I thought about the implementation.
In short, I would suggest to have one page which lists all processes that require a review.
If the approver clicks on one of the processes in the list, the application switches the page to a details page where you ONLY see the one process and can comment, approve or reject (deny) the process. Besides, relevant information about the process should also be shown there.

Nevertheless, I will approve this PR BUT it is still incomplete. Thus, as soon as the backend is providing all the necessary endpoints, this issue needs to be implemented well.

2018-06-21 12:58 UTC, amarbajric approved these changes
Needs further implementation as soon as endpoints are available

2018-06-21 12:59 UTC, merged